#pragma once
#include <vector>
#include <iostream>
#include "Option.h"

//This Class is a Monte Carlo Pricer
class RandomPaths
{
public:
	RandomPaths(int nSimul, double r, double sigma, double s0, double steps, Option& option); 

	//methods
	double boxMuller();
	double getPayoff(double K, int n);
	
	double pricerPathDependent(EuropeanOption& option);

	double pricerPathDependent(AsianOption& option);


private:
	std::vector<std::vector<double>> paths_; //vector of random paths generated by black-Sholes Dynamic
	double _r;
	double _sigma;
	double _s0;
	double _steps;
	int nSimul_; //number of simulation
};